semester: "Fall 2021"
title: "CS 817: Selected Topics in Systems Research"
desc: "JHU Selected Topics in Systems Research"
date_time: "Fridays 1:30-2:45pm"
location: "Malone 338"
instructor: "Prof. Ryan Huang"
instructor_homepage: https://www.cs.jhu.edu/~huang
email: huang@cs.jhu.edu

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
